%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\meroo\OneDrive - UMBC\Research\Data\Pandora\Pandonia\Use\Pandora32s1_GreenbeltMD_L2Tot_rout0p1-7.txt
%
% Auto-generated by MATLAB on 04-Apr-2020 13:52:05

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = [22, 65];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["FilenamePandora32s1_GreenbeltMD_L2Tot_rout0p17txt", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12"];
opts.VariableTypes = ["char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["FilenamePandora32s1_GreenbeltMD_L2Tot_rout0p17txt", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["FilenamePandora32s1_GreenbeltMD_L2Tot_rout0p17txt", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12"], "EmptyFieldRule", "auto");

% Import the data
Pandonia32s1_headers = readtable("C:\Users\meroo\OneDrive - UMBC\Research\Data\Pandora\Pandonia\Use\Pandora32s1_GreenbeltMD_L2Tot_rout0p1-7.txt", opts);

%% Convert to output type
Pandonia32s1_headers = table2cell(Pandonia32s1_headers);
numIdx = cellfun(@(x) ~isnan(str2double(x)), Pandonia32s1_headers);
Pandonia32s1_headers(numIdx) = cellfun(@(x) {str2double(x)}, Pandonia32s1_headers(numIdx));

%% Clear temporary variables
clear opts

%% Save as .mat file
path = 'C:\Users\meroo\OneDrive - UMBC\Research\Data\Processed\';
save([path 'Pandonia_Pan32s1.mat'], 'Pandonia')
save([path 'Pandonia_Pan32s1_headers.mat'], 'Pandonia32s1_headers')